apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::956441097735:role/eksctl-eksctl-demo-nodegroup-ng-f-NodeInstanceRole-PQQZS1V7EIJ0
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-03T15:25:38Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1538"
  uid: 55a8a8de-b9f4-44a1-9bbe-c75b24bdc34b
