apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::956441097735:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1DEP0MMEYZ6X0
      username: system:node:{{EC2PrivateDNSName}}

    - groups:
      - system:masters
      rolearn: arn:aws:iam::956441097735:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-04T08:21:27Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1548"
  uid: cbc67991-d22e-421f-aee9-e8cd726ee980
